---
- name: vCloud Migration - Create Transfer Hub
  hosts: localhost
  become: false
  roles:
    - transfer_hub

- name: vCloud Migration - Create Workspaces
  hosts: migrate_vapps
  become: false
  serial: 1
  roles:
    - create_workspace

- name: vCloud Migration - Prepare VMs for export
  hosts: migrate_vapps
  become: true
  roles:
    - prepare_export

    # - name: migrate_instance
    #   with_items: "{{ instances }}"
    #   include_role:
    #     name: migrate_instance
    #   vars:
    #     instance: "{{ item }}"